package com.yaz.sms.core.sms

/**
 * What an iPhone sends as SMS when someone reacts to a message: a sentence
 * in the phone's language around the quoted message ("Loved “See you”",
 * "A adoré « See you »", "Reacted 👀 to “See you”"). Apple's own wording
 * for every language iOS speaks, the six classic reactions, any emoji since
 * iOS 18, and their removals; the quotes and spaces of any language accepted.
 */
internal object Tapbacks {

    /** [emoji] empty: the emoji is in the sentence (the first %@ of the English). */
    private class Form(val lang: String, val text: String, val emoji: String, val removed: Boolean)

    private class Pattern(val regex: Regex, val emoji: String, val emojiGroup: Int, val quoteGroup: Int, val removed: Boolean)

    private const val QUOTES = "\"“”„‟«»‹›「」『』'‘’‚"

    private val patterns: List<Pattern> by lazy { FORMS.mapNotNull(::compile) }

    /** Quick look before the patterns: a reaction quotes something. */
    fun mayBe(body: String): Boolean = body.length in 4..2000 && body.any { it in QUOTES }

    fun parse(body: String): SmsReactions.Parsed? {
        if (!mayBe(body)) return null
        for (p in patterns) {
            val m = p.regex.matchEntire(body) ?: continue
            val emoji = if (p.emojiGroup > 0) m.groupValues[p.emojiGroup].trim() else p.emoji
            // "Reacted with a sticker", words where an emoji should be: not ours to show.
            if (emoji.isEmpty() || emoji.any { it.isLetter() }) continue
            return SmsReactions.Parsed(emoji, m.groupValues[p.quoteGroup].trim { it.isWhitespace() || it in "\u200b\u200c\u200d\u200e\u200f\u2066\u2067\u2068\u2069" }, p.removed)
        }
        return null
    }

    /**
     * One form as a pattern: %@ (or %1$@, %2$@ when a language swaps them) for
     * the emoji and the quoted message; any quote mark for a quote mark, any
     * space for a space, a final full stop optional.
     */
    private fun compile(form: Form): Pattern? {
        val parts = Regex("%(\\d)?\\$?@").findAll(form.text).toList()
        val expected = if (form.emoji.isEmpty()) 2 else 1
        if (parts.size != expected) return null
        val sb = StringBuilder("(?s)[\\s\\u200a-\\u200f\\u2066-\\u2069]*")
        var at = 0
        var emojiGroup = 0
        var quoteGroup = 0
        parts.forEachIndexed { i, p ->
            sb.append(literal(form.text.substring(at, p.range.first)))
            val index = p.groupValues[1].toIntOrNull() ?: (i + 1)
            if (form.emoji.isEmpty() && index == 1) {
                emojiGroup = i + 1
                sb.append("(.+?)")
            } else {
                quoteGroup = i + 1
                sb.append("(.+)")
            }
            at = p.range.last + 1
        }
        sb.append(literal(form.text.substring(at).trimEnd('.', '。', '։', '۔'))).append("[.。։۔]?[\\s\\u200a-\\u200f\\u2066-\\u2069]*")
        if (quoteGroup == 0) return null
        return Pattern(Regex(sb.toString()), form.emoji, emojiGroup, quoteGroup, form.removed)
    }

    private fun literal(text: String): String = buildString {
        for (c in text) when {
            c in QUOTES -> append("[").append(QUOTES).append("]")
            // Marks for the layout of a language (hair spaces, joiners, direction): there or not.
            c in '\u200a'..'\u200f' || c in '\u2066'..'\u2069' -> append("[\\u200a-\\u200f\\u2066-\\u2069]*")
            c.isWhitespace() || c == '\u00a0' || c == '\u202f' -> append("[\\s\\u00a0\\u202f]*")
            else -> append(Regex.escape(c.toString()))
        }
    }

    // Generated from Apple's own wording (iOS, IMSharedUtilities), one line per language and form.
    private val FORMS = listOf(
        Form("ar", "أحبَّ(ت) \"%@\"", "❤️", false),
        Form("bg", "Реагира със сърце на „%@“", "❤️", false),
        Form("bn", "“%@”-এ ভালোবাসার প্রতিক্রিয়া দিয়েছেন", "❤️", false),
        Form("ca", "Li ha encantat “%@”.", "❤️", false),
        Form("cs", "K\u00a0„%@“ bylo přidáno srdíčko", "❤️", false),
        Form("da", "Føjede et hjerte til “%@”", "❤️", false),
        Form("de", "„%@“ ein Herz hinzugefügt", "❤️", false),
        Form("el", "Του/Της αρέσει πολύ το «%@»", "❤️", false),
        Form("en", "Loved “%@”", "❤️", false),
        Form("es", "Le encanta “%@”", "❤️", false),
        Form("es_419", "Le encantó “%@”", "❤️", false),
        Form("fi", "Viesti ”%@” merkittiin sydämellä", "❤️", false),
        Form("fr", "A ajouté un «\u00a0J’adore\u00a0» à «\u00a0%@\u00a0».", "❤️", false),
        Form("fr_CA", "a attribué la mention «\u00a0Adore\u00a0» à «\u00a0%@\u00a0»", "❤️", false),
        Form("gu", "“%@”ને પસંદ કર્યું", "❤️", false),
        Form("he", "הוסיף/ה לב ל: ״%@״", "❤️", false),
        Form("hi", "ने “%@” को बहुत पसंद किया", "❤️", false),
        Form("hr", "Korisnik obožava “%@”", "❤️", false),
        Form("hu", "Szereti ezt: „%@”", "❤️", false),
        Form("id", "Mencintai “%@”", "❤️", false),
        Form("it", "Ha aggiunto un cuoricino a “%@”", "❤️", false),
        Form("ja", "“%@”に「ハート」と応答", "❤️", false),
        Form("kk", "«%@» дегенді қатты ұнатты", "❤️", false),
        Form("kn", "“%@” ಅನ್ನು ಇಷ್ಟಪಟ್ಟಿದ್ದಾರೆ", "❤️", false),
        Form("ko", "‘%@’에 하트 표시", "❤️", false),
        Form("lt", "Labai patiko „%@“", "❤️", false),
        Form("ml", "‘%@’ എന്നതിൽ സ്നേഹം പ്രകടിപ്പിച്ചു", "❤️", false),
        Form("mr", "‘%@’ ला जास्त पसंत केले आहे", "❤️", false),
        Form("ms", "Menggemari “%@”", "❤️", false),
        Form("nl", "Gaf een hartje aan '%@'", "❤️", false),
        Form("no", "Satte et hjerte ved «%@»", "❤️", false),
        Form("or", "“%@”ଭଲ ପାଇଛନ୍ତି", "❤️", false),
        Form("pa", "%@ ਨੂੰ ਬਹੁਤ ਪਸੰਦ ਕੀਤਾ ਗਿਆ", "❤️", false),
        Form("pl", "Dodano „serce” do „%@”", "❤️", false),
        Form("pt", "Gostou de “%@”", "❤️", false),
        Form("pt_PT", "Adorou “%@”", "❤️", false),
        Form("ro", "A apreciat „%@”", "❤️", false),
        Form("ru", "Очень понравилось «%@»", "❤️", false),
        Form("sk", "Na „%@“ bolo pridané srdce", "❤️", false),
        Form("sl", "Element »%@« je označen kot »Pri srcu mi je«", "❤️", false),
        Form("sv", "Gav ett hjärta till ”%@”", "❤️", false),
        Form("ta", "“%@”க்கு இதய இமோஜி அளிக்கப்பட்டது", "❤️", false),
        Form("te", "“%@”కు ఇష్టం గుర్తు చేర్చబడింది", "❤️", false),
        Form("th", "ชอบ “%@”", "❤️", false),
        Form("tr", "Kalp eklendi: “%@”", "❤️", false),
        Form("uk", "У захваті від «%@»", "❤️", false),
        Form("ur", "نے \u200f“%@” کو بہت پسند کیا", "❤️", false),
        Form("vi", "Đã yêu thích “%@”", "❤️", false),
        Form("zh_CN", "比心：%@", "❤️", false),
        Form("zh_HK", "喜愛「%@」", "❤️", false),
        Form("ar", "وضع(ت) إعجابًا على \"%@\"", "👍", false),
        Form("bg", "Хареса „%@“", "👍", false),
        Form("bn", "“%@”-এ লাইক দিয়েছেন", "👍", false),
        Form("ca", "Li ha agradat “%@”.", "👍", false),
        Form("cs", "K\u00a0„%@“ bylo přidáno označení líbí", "👍", false),
        Form("da", "Syntes om “%@”", "👍", false),
        Form("de", "Gefällt: „%@“", "👍", false),
        Form("el", "Του/Της αρέσει το «%@»", "👍", false),
        Form("en", "Liked “%@”", "👍", false),
        Form("es", "Le gusta “%@”", "👍", false),
        Form("es_419", "Le gustó “%@”", "👍", false),
        Form("fi", "Viestistä ”%@” tykättiin", "👍", false),
        Form("fr", "A ajouté un «\u00a0J’aime\u00a0» à «\u00a0%@\u00a0».", "👍", false),
        Form("fr_CA", "a attribué la mention «\u00a0Aime\u00a0» à «\u00a0%@\u00a0»", "👍", false),
        Form("gu", "“%@”ને લાઇક કર્યું", "👍", false),
        Form("he", "הוסיף/ה סימון ״אהבתי״ ל: ״%@״", "👍", false),
        Form("hi", "ने “%@” को पसंद किया", "👍", false),
        Form("hr", "Korisniku se sviđa “%@”", "👍", false),
        Form("hu", "Kedveli: „%@”", "👍", false),
        Form("id", "Menyukai “%@”", "👍", false),
        Form("it", "Ha aggiunto “Mi piace” a “%@”", "👍", false),
        Form("ja", "“%@”に「いいね」と応答", "👍", false),
        Form("kk", "«%@» дегенді ұнатты", "👍", false),
        Form("kn", "“%@” ಅನ್ನು ಲೈಕ್ ಮಾಡಿದ್ದಾರೆ", "👍", false),
        Form("ko", "‘%@’에 좋아요 표시함", "👍", false),
        Form("lt", "Pažymėjo, kad patinka „%@“", "👍", false),
        Form("ml", "‘%@’ എന്നതിനെ ലൈക്ക് ചെയ്തു", "👍", false),
        Form("mr", "‘%@’ ला पसंत केले आहे", "👍", false),
        Form("nl", "Vond '%@' leuk", "👍", false),
        Form("no", "Likte «%@»", "👍", false),
        Form("or", "“%@” ପସନ୍ଦ କରିଛନ୍ତି", "👍", false),
        Form("pa", "“%@” ਨੂੰ ਪਸੰਦ ਕੀਤਾ ਗਿਆ", "👍", false),
        Form("pl", "Dodano „kciuk w\u00a0górę” do „%@”", "👍", false),
        Form("pt", "Curtiu “%@”", "👍", false),
        Form("pt_PT", "Gostou de “%@”", "👍", false),
        Form("ro", "A aprobat „%@”", "👍", false),
        Form("ru", "Понравилось «%@»", "👍", false),
        Form("sk", "Na „%@“ bolo pridané označenie páči sa", "👍", false),
        Form("sl", "Element »%@« je označen kot »Všeč mi je«", "👍", false),
        Form("sv", "Gillade ”%@”", "👍", false),
        Form("ta", "“%@”க்கு விருப்பம் தெரிவிக்கப்பட்டது", "👍", false),
        Form("te", "“%@” లైక్ చేయబడింది", "👍", false),
        Form("th", "ถูกใจ “%@”", "👍", false),
        Form("tr", "Beğenildi: “%@”", "👍", false),
        Form("uk", "Подобається «%@»", "👍", false),
        Form("ur", "نے \u200f“%@” کو پسند کیا", "👍", false),
        Form("vi", "Đã thích “%@”", "👍", false),
        Form("zh_CN", "赞了：%@", "👍", false),
        Form("zh_HK", "讚好「%@」", "👍", false),
        Form("zh_TW", "喜歡「%@」", "👍", false),
        Form("ar", "وضع(ت) عدم إعجاب على \"%@\"", "👎", false),
        Form("bg", "Не хареса „%@“", "👎", false),
        Form("bn", "“%@” ডিসলাইক করেছেন", "👎", false),
        Form("ca", "No li ha agradat “%@”.", "👎", false),
        Form("cs", "K\u00a0„%@“ bylo přidáno označení nelíbí", "👎", false),
        Form("da", "Syntes ikke om “%@”", "👎", false),
        Form("de", "Gefällt nicht: „%@“", "👎", false),
        Form("el", "Δεν του/της αρέσει το «%@»", "👎", false),
        Form("en", "Disliked “%@”", "👎", false),
        Form("es", "No le gusta “%@”", "👎", false),
        Form("es_419", "No le gustó “%@”", "👎", false),
        Form("fi", "Viestistä ”%@” ei tykätty", "👎", false),
        Form("fr", "A ajouté un «\u00a0Je n’aime pas\u00a0» à «\u00a0%@\u00a0».", "👎", false),
        Form("fr_CA", "a attribué la mention «\u00a0N’aime pas\u00a0» à «\u00a0%@\u00a0»", "👎", false),
        Form("gu", "“%@”ને ડિસલાઇક કર્યું", "👎", false),
        Form("he", "הוסיף/ה סימון ״לא אהבתי״ ל: ״%@״", "👎", false),
        Form("hi", "ने “%@” को नापसंद किया", "👎", false),
        Form("hr", "Korisniku se ne sviđa “%@”", "👎", false),
        Form("hu", "Nem kedveli: „%@”", "👎", false),
        Form("id", "Tidak menyukai “%@”", "👎", false),
        Form("it", "Ha aggiunto “Non mi piace” a “%@”", "👎", false),
        Form("ja", "“%@”に「よくないね」と応答", "👎", false),
        Form("kk", "«%@» ұнамады", "👎", false),
        Form("kn", "“%@” ಡಿಸ್\u200cಲೈಕ್ ಮಾಡಿದ್ದಾರೆ", "👎", false),
        Form("ko", "‘%@’에 별로예요 표시함", "👎", false),
        Form("lt", "Pažymėjo, kad „%@“ nepatinka", "👎", false),
        Form("ml", "‘%@’ എന്നതിനെ ഡിസ്\u200cലൈക്ക് ചെയ്തു", "👎", false),
        Form("mr", "‘%@’ ला नापसंत केले आहे", "👎", false),
        Form("ms", "Menyahsuka “%@”", "👎", false),
        Form("nl", "Vond '%@' niet leuk", "👎", false),
        Form("no", "Mislikte «%@»", "👎", false),
        Form("or", "“%@” ନାପସନ୍ଦ କରିଛନ୍ତି", "👎", false),
        Form("pa", "”%@” ਨੂੰ ਨਾਪਸੰਦ ਕੀਤਾ ਗਿਆ", "👎", false),
        Form("pl", "Dodano „kciuk w\u00a0dół” do „%@”", "👎", false),
        Form("pt", "Não curtiu “%@”", "👎", false),
        Form("pt_PT", "Não gostou de “%@”", "👎", false),
        Form("ro", "A dezaprobat „%@”", "👎", false),
        Form("ru", "Не понравилось «%@»", "👎", false),
        Form("sk", "Na „%@“ bolo pridané označenie nepáči sa", "👎", false),
        Form("sl", "Element »%@« je označen kot »Ni mi všeč«", "👎", false),
        Form("sv", "Ogillade ”%@”", "👎", false),
        Form("ta", "“%@”க்கு விருப்பமின்மை தெரிவிக்கப்பட்டது", "👎", false),
        Form("te", "“%@”కు డిస్\u200cలైక్ చేయబడింది", "👎", false),
        Form("th", "ไม่ถูกใจ “%@”", "👎", false),
        Form("tr", "Beğenilmedi: “%@”", "👎", false),
        Form("uk", "Не подобається «%@»", "👎", false),
        Form("ur", "نے \u200f“%@” کو ناپسند کیا", "👎", false),
        Form("vi", "Đã không thích “%@”", "👎", false),
        Form("zh_CN", "踩了：%@", "👎", false),
        Form("zh_HK", "不喜歡「%@」", "👎", false),
        Form("ar", "ضحك(ت) على \"%@\"", "😂", false),
        Form("bg", "Реагира със смях на „%@“", "😂", false),
        Form("bn", "“%@”-এ হাসির প্রতিক্রিয়া দিয়েছেন", "😂", false),
        Form("ca", "Li ha fet gràcia “%@”.", "😂", false),
        Form("cs", "K\u00a0„%@“ byl přidán smích", "😂", false),
        Form("da", "Grinede af “%@”", "😂", false),
        Form("de", "„%@“ ein Lachen hinzugefügt", "😂", false),
        Form("el", "Γέλασε με «%@»", "😂", false),
        Form("en", "Laughed at “%@”", "😂", false),
        Form("es", "Le hace gracia “%@”", "😂", false),
        Form("es_419", "Le dio risa “%@”", "😂", false),
        Form("fi", "Viestille ”%@” naurahdettiin", "😂", false),
        Form("fr", "A ajouté un rire à «\u00a0%@\u00a0».", "😂", false),
        Form("fr_CA", "a attribué la mention «\u00a0Rires\u00a0» à «\u00a0%@\u00a0»", "😂", false),
        Form("gu", "“%@” પર હસ્યા", "😂", false),
        Form("he", "הוסיף/ה צחקוק ל: ״%@״", "😂", false),
        Form("hi", "ने “%@” पर ठहाका लगाया", "😂", false),
        Form("hr", "Korisniku je smiješno: “%@”", "😂", false),
        Form("hu", "Nevetett ezen: „%@”", "😂", false),
        Form("id", "Menertawai “%@”", "😂", false),
        Form("it", "Trova divertente “%@”", "😂", false),
        Form("ja", "“%@”に「笑」と応答", "😂", false),
        Form("kk", "«%@» дегенге күлді", "😂", false),
        Form("kn", "“%@” ನೋಡಿ ನಗೆ ಬೀರಿದ್ದಾರೆ", "😂", false),
        Form("ko", "‘%@’에 웃음 표시", "😂", false),
        Form("lt", "Juokėsi iš „%@“", "😂", false),
        Form("ml", "‘%@’ എന്നതിൽ ചിരിച്ചു", "😂", false),
        Form("mr", "‘%@’ वर हसलात", "😂", false),
        Form("ms", "Mengetawakan “%@”", "😂", false),
        Form("nl", "Lachte om '%@'", "😂", false),
        Form("no", "Lo av «%@»", "😂", false),
        Form("or", "“%@” ଉପରେ ହସିଛନ୍ତି", "😂", false),
        Form("pa", "”%@” ‘ਤੇ ਠਹਾਕਾ ਲਗਾਇਆ ਗਿਆ", "😂", false),
        Form("pl", "Dodano „śmiech” do „%@”", "😂", false),
        Form("pt", "Riu de “%@”", "😂", false),
        Form("pt_PT", "Riu‑se de “%@”", "😂", false),
        Form("ro", "A râs de „%@”", "😂", false),
        Form("ru", "Посмеялись над\u00a0«%@»", "😂", false),
        Form("sk", "Na „%@“ bol pridaný smiech", "😂", false),
        Form("sl", "Element »%@« je označen kot »Smešno«", "😂", false),
        Form("sv", "Skrattade åt ”%@”", "😂", false),
        Form("ta", "“%@”க்குச் சிரிப்பு இமோஜி பயன்படுத்தப்பட்டது", "😂", false),
        Form("te", "“%@”కు నవ్వుతున్న ఎమోజీ చేర్చబడింది", "😂", false),
        Form("th", "หัวเราะให้กับ “%@”", "😂", false),
        Form("tr", "Gülme işareti eklendi: “%@”", "😂", false),
        Form("uk", "Сміється з «%@»", "😂", false),
        Form("ur", "کو \u200f“%@” پر ہنسی آئی", "😂", false),
        Form("vi", "Đã cười về “%@”", "😂", false),
        Form("zh_CN", "觉得很好笑：%@", "😂", false),
        Form("zh_HK", "覺得好笑：「%@」", "😂", false),
        Form("zh_TW", "大笑「%@」", "😂", false),
        Form("ar", "أكَّد(ت) على \"%@\"", "‼️", false),
        Form("bg", "Реагира с удивителна на „%@“", "‼️", false),
        Form("bn", "“%@”-এর উপর গুরুত্ব আরোপ করা হয়েছে", "‼️", false),
        Form("ca", "L’ha sorprès “%@”.", "‼️", false),
        Form("cs", "K\u00a0„%@“ byl přidán vykřičník", "‼️", false),
        Form("da", "Føjede udråbstegn til “%@”", "‼️", false),
        Form("de", "„%@“ ein Ausrufezeichen hinzugefügt", "‼️", false),
        Form("el", "Έδωσε έμφαση στο «%@»", "‼️", false),
        Form("en", "Emphasized “%@”", "‼️", false),
        Form("en_AU", "Emphasised “%@”", "‼️", false),
        Form("es", "Le sorprende “%@”", "‼️", false),
        Form("es_419", "Exclamó por “%@”", "‼️", false),
        Form("fi", "Viestiin ”%@” lisättiin huutomerkki", "‼️", false),
        Form("fr", "A ajouté des points d’exclamation à «\u00a0%@\u00a0».", "‼️", false),
        Form("fr_CA", "a attribué la mention «\u00a0Exclamation\u00a0» à «\u00a0%@\u00a0»", "‼️", false),
        Form("gu", "“%@”ને મહત્ત્વ આપ્યું", "‼️", false),
        Form("he", "הוסיף/ה סימני קריאה ל: ״%@״", "‼️", false),
        Form("hi", "ने “%@” को महत्व दिया", "‼️", false),
        Form("hr", "Korisnik naglašava “%@”", "‼️", false),
        Form("hu", "Kiemelte: „%@”", "‼️", false),
        Form("id", "Mempertegas “%@”", "‼️", false),
        Form("it", "Ha aggiunto i punti esclamativi a “%@”", "‼️", false),
        Form("ja", "“%@”に「!!」と応答", "‼️", false),
        Form("kk", "«%@» белгіледі", "‼️", false),
        Form("kn", "“%@” ಅನ್ನು ಎಂಫಸೈಸ್ ಮಾಡಿದ್ದಾರೆ", "‼️", false),
        Form("ko", "‘%@’에 느낌표 표시", "‼️", false),
        Form("lt", "Pabrėžė „%@“", "‼️", false),
        Form("ml", "‘%@’ പ്രധാനമാക്കി", "‼️", false),
        Form("mr", "‘%@‘ वर एम्फसाईज्ड केले आहे", "‼️", false),
        Form("ms", "Menekankan “%@”", "‼️", false),
        Form("nl", "Benadrukte '%@'", "‼️", false),
        Form("no", "Satte utropstegn ved «%@»", "‼️", false),
        Form("or", "“%@” ଗୁରୁତ୍ୱ ଦେଇଛନ୍ତି", "‼️", false),
        Form("pa", "%@ ਨੂੰ ਮਹੱਤਵ ਦਿੱਤਾ ਗਿਆ", "‼️", false),
        Form("pl", "Dodano „wykrzykniki” do „%@”", "‼️", false),
        Form("pt", "Enfatizou “%@”", "‼️", false),
        Form("ro", "A accentuat „%@”", "‼️", false),
        Form("ru", "Отмечено «%@»", "‼️", false),
        Form("sk", "Na „%@“ bol pridaný výkričník", "‼️", false),
        Form("sl", "Element »%@« je poudarjen", "‼️", false),
        Form("sv", "Betonade ”%@”", "‼️", false),
        Form("ta", "“%@”க்கு இருஆச்சரியக்குறி இமோஜி சேர்க்கப்பட்டது", "‼️", false),
        Form("te", "“%@”కు ప్రాధాన్యత గుర్తు చేర్చబడింది", "‼️", false),
        Form("th", "ตกใจ “%@”", "‼️", false),
        Form("tr", "Ünlem işareti eklendi: “%@”", "‼️", false),
        Form("uk", "Акцентовано «%@»", "‼️", false),
        Form("ur", "نے \u200f“%@” کو اہمیت دی", "‼️", false),
        Form("vi", "Đã nhấn mạnh “%@”", "‼️", false),
        Form("zh_CN", "很惊叹：%@", "‼️", false),
        Form("zh_HK", "驚嘆「%@」", "‼️", false),
        Form("ar", "تساءل(ت) عن \"%@\"", "❓", false),
        Form("bg", "Реагира с въпросителна на „%@“", "❓", false),
        Form("bn", "“%@”-এ প্রশ্নবোধক চিহ্ন দেওয়া হয়েছে", "❓", false),
        Form("ca", "Té dubtes sobre “%@”.", "❓", false),
        Form("cs", "K\u00a0„%@“ byl přidán otazník", "❓", false),
        Form("da", "Føjede et spørgsmålstegn til “%@”", "❓", false),
        Form("de", "„%@“ ein Fragezeichen hinzugefügt", "❓", false),
        Form("el", "Αναρωτήθηκε για «%@»", "❓", false),
        Form("en", "Questioned “%@”", "❓", false),
        Form("es", "Duda sobre “%@”", "❓", false),
        Form("es_419", "Dudó sobre “%@”", "❓", false),
        Form("fi", "Viestiin ”%@” lisättiin kysymysmerkki", "❓", false),
        Form("fr", "A ajouté un point d’interrogation à «\u00a0%@\u00a0».", "❓", false),
        Form("fr_CA", "a attribué la mention «\u00a0Question\u00a0» à «\u00a0%@\u00a0»", "❓", false),
        Form("gu", "“%@” પર પ્રશ્ન કર્યો", "❓", false),
        Form("he", "הוסיף/ה סימן שאלה ל: ״%@״", "❓", false),
        Form("hi", "ने “%@” को प्रश्नांकित किया", "❓", false),
        Form("hr", "Korisnik dovodi u pitanje “%@”", "❓", false),
        Form("hu", "Rákérdezett erre: „%@”", "❓", false),
        Form("id", "Mempertanyakan “%@”", "❓", false),
        Form("it", "Ha aggiunto il punto interrogativo a “%@”", "❓", false),
        Form("ja", "“%@”に「?」と応答", "❓", false),
        Form("kk", "«%@» дегенге сұрақ қойылды", "❓", false),
        Form("kn", "“%@” ಅನ್ನು ಪ್ರಶ್ನಿಸಿದ್ದಾರೆ", "❓", false),
        Form("ko", "‘%@’에 물음표 표시", "❓", false),
        Form("lt", "Abejojo dėl „%@“", "❓", false),
        Form("ml", "‘%@’ എന്നതിൽ ചോദ്യചിഹ്നമിട്ടു", "❓", false),
        Form("mr", "‘%@’ला प्रश्नांकित केले आहे", "❓", false),
        Form("ms", "Menyoal “%@”", "❓", false),
        Form("nl", "Zette een vraagteken bij '%@'", "❓", false),
        Form("no", "Satte spørsmålstegn ved «%@»", "❓", false),
        Form("or", "“%@”ପ୍ରଶ୍ନ କରିଛନ୍ତି", "❓", false),
        Form("pa", "”%@” ‘ਤੇ ਸਵਾਲ ਕੀਤਾ ਗਿਆ", "❓", false),
        Form("pl", "Dodano „znak zapytania” do „%@”", "❓", false),
        Form("pt", "Questionou “%@”", "❓", false),
        Form("ro", "A chestionat „%@”", "❓", false),
        Form("ru", "Поставлен вопрос на\u00a0«%@»", "❓", false),
        Form("sk", "Na „%@“ bol pridaný otáznik", "❓", false),
        Form("sl", "Element »%@« je označen z vprašajem", "❓", false),
        Form("sv", "Satte ett frågetecken på ”%@”", "❓", false),
        Form("ta", "“%@”க்குக் கேள்விக்குறி சேர்க்கப்பட்டது", "❓", false),
        Form("te", "“%@”కు ప్రశ్నార్థక గుర్తు చేర్చబడింది", "❓", false),
        Form("th", "ตั้งคำถาม “%@”", "❓", false),
        Form("tr", "Soru işareti eklendi: “%@”", "❓", false),
        Form("uk", "Піддає сумніву «%@»", "❓", false),
        Form("ur", "نے \u200f“%@” پر سوال کیا", "❓", false),
        Form("vi", "Đã nghi vấn “%@”", "❓", false),
        Form("zh_CN", "很疑惑：%@", "❓", false),
        Form("zh_HK", "有疑惑「%@」", "❓", false),
        Form("zh_TW", "疑惑「%@」", "❓", false),
        Form("ar", "أزال(ت) قلبًا عن \"%@\"", "❤️", true),
        Form("bg", "Премахна сърце от „%@“", "❤️", true),
        Form("bn", "“%@”-এর থেকে একটি হৃদয় চিহ্ন সরানো হয়েছে", "❤️", true),
        Form("ca", "Ja no li encanta “%@”.", "❤️", true),
        Form("cs", "Z\u00a0„%@“ bylo odstraněno srdíčko", "❤️", true),
        Form("da", "Fjernede et hjerte fra “%@”", "❤️", true),
        Form("de", "Herz von „%@“ entfernt", "❤️", true),
        Form("el", "Αφαίρεσε την καρδούλα από «%@»", "❤️", true),
        Form("en", "Removed a heart from “%@”", "❤️", true),
        Form("es", "Ya no le encanta “%@”", "❤️", true),
        Form("es_419", "Dejó de encantarle “%@”", "❤️", true),
        Form("fi", "Viestistä ”%@” poistettiin sydän", "❤️", true),
        Form("fr", "A retiré son «\u00a0J’adore\u00a0» de «\u00a0%@\u00a0».", "❤️", true),
        Form("fr_CA", "a retiré la mention «\u00a0Adore\u00a0» de «\u00a0%@\u00a0»", "❤️", true),
        Form("gu", "“%@”માંથી દિલ કાઢી નાખ્યું", "❤️", true),
        Form("he", "הסיר/ה לב מ: ״%@״", "❤️", true),
        Form("hi", "ने “%@” से दिल को हटाया", "❤️", true),
        Form("hr", "Korisnik uklanja srce sa “%@”", "❤️", true),
        Form("hu", "Eltávolított egy szívet erről: „%@”", "❤️", true),
        Form("id", "Menghapus hati dari “%@”", "❤️", true),
        Form("it", "Ha rimosso il cuoricino da “%@”", "❤️", true),
        Form("ja", "“%@”から「ハート」を削除", "❤️", true),
        Form("kk", "«%@» дегеннен жүрекшені алып тастады", "❤️", true),
        Form("kn", "“%@” ಸಂದೇಶದಿಂದ ಹಾರ್ಟ್ ತೆಗೆದುಹಾಕಿದ್ದಾರೆ", "❤️", true),
        Form("ko", "‘%@’에서 하트 표시 제거함", "❤️", true),
        Form("lt", "Pašalino „%@“ širdies jaustuką", "❤️", true),
        Form("ml", "‘%@’ എന്നതിൽ നിന്ന് ഹൃദയം നീക്കം ചെയ്തു", "❤️", true),
        Form("mr", "‘%@’ वरून हृदय काढून टाकले आहे", "❤️", true),
        Form("ms", "Mengeluarkan hati daripada “%@”", "❤️", true),
        Form("nl", "Verwijderde een hartje van '%@'", "❤️", true),
        Form("no", "Fjernet et hjerte fra «%@»", "❤️", true),
        Form("or", "“%@” ରୁ ଗୋଟିଏ ହୃଦୟ କାଢ଼ିଛନ୍ତି", "❤️", true),
        Form("pa", "”%@” ਤੋਂ ਦਿਲ ਨੂੰ ਹਟਾਇਆ ਗਿਆ", "❤️", true),
        Form("pl", "Usunięto „serce” z\u00a0„%@”", "❤️", true),
        Form("pt", "Removeu um coração de “%@”", "❤️", true),
        Form("ro", "A eliminat o apreciere pentru „%@”", "❤️", true),
        Form("ru", "Отметка «Очень нравится» убрана с\u00a0«%@»", "❤️", true),
        Form("sk", "Z\u00a0„%@“ bolo odstránené srdce", "❤️", true),
        Form("sl", "Z elementa »%@« je bila odstranjena oznaka »Pri srcu mi je«", "❤️", true),
        Form("sv", "Tog bort ett hjärta från ”%@”", "❤️", true),
        Form("ta", "“%@”இலிருந்து இதய இமோஜி அகற்றப்பட்டது", "❤️", true),
        Form("te", "“%@”కి ఇష్టం మార్క్ తొలగించబడింది", "❤️", true),
        Form("th", "เอาหัวใจออกจาก “%@”", "❤️", true),
        Form("tr", "Kalp silindi: “%@”", "❤️", true),
        Form("uk", "Вилучено «серце» з «%@»", "❤️", true),
        Form("ur", "نے \u200f“%@” سے دل کو ہٹایا", "❤️", true),
        Form("vi", "Đã xóa trái tim khỏi “%@”", "❤️", true),
        Form("zh_CN", "收回了心：%@", "❤️", true),
        Form("zh_HK", "不再喜愛「%@」", "❤️", true),
        Form("zh_TW", "已收回喜愛「%@」", "❤️", true),
        Form("ar", "أزال(ت) إعجابًا عن \"%@\"", "👍", true),
        Form("bg", "Премахна харесване от „%@“", "👍", true),
        Form("bn", "“%@” থেকে একটি লাইক সরানো হয়েছে", "👍", true),
        Form("ca", "Ja no li agrada “%@”.", "👍", true),
        Form("cs", "Z\u00a0„%@“ bylo odstraněno označení líbí", "👍", true),
        Form("da", "Fjernede et synes om fra “%@”", "👍", true),
        Form("de", "„Gefällt mir“ von „%@“ entfernt", "👍", true),
        Form("el", "Αφαίρεσε το «μου αρέσει» από «%@»", "👍", true),
        Form("en", "Removed a like from “%@”", "👍", true),
        Form("es", "Ya no le gusta “%@”", "👍", true),
        Form("es_419", "Dejó de gustarle “%@”", "👍", true),
        Form("fi", "Viestistä ”%@” poistettiin tykkäys", "👍", true),
        Form("fr", "A retiré son «\u00a0J’aime\u00a0» de «\u00a0%@\u00a0».", "👍", true),
        Form("fr_CA", "a retiré la mention «\u00a0Aime\u00a0» de «\u00a0%@\u00a0»", "👍", true),
        Form("gu", "“%@”માંથી લાઇક કાઢી નાખી", "👍", true),
        Form("he", "הסיר/ה סימון ״אהבתי״ מ: ״%@״", "👍", true),
        Form("hi", "ने “%@” से पसंद को हटाया", "👍", true),
        Form("hr", "Korisnik uklanja oznaku “Sviđa mi se” sa “%@”", "👍", true),
        Form("hu", "Eltávolított egy kedvelést erről: „%@”", "👍", true),
        Form("id", "Menghapus suka dari “%@”", "👍", true),
        Form("it", "Ha rimosso “Mi piace” da “%@”", "👍", true),
        Form("ja", "“%@”から「いいね」を削除", "👍", true),
        Form("kk", "%@ дегеннен ұнату белгісін алып тастады", "👍", true),
        Form("kn", "“%@” ಸಂದೇಶದಿಂದ ಲೈಕ್ ತೆಗೆದುಹಾಕಿದ್ದಾರೆ", "👍", true),
        Form("ko", "‘%@’에서 좋아요 표시 제거함", "👍", true),
        Form("lt", "Pašalino žymėjimą, kad patinka „%@“", "👍", true),
        Form("ml", "‘%@’ എന്നതിൽ നിന്ന് ലൈക്ക് നീക്കം ചെയ്തു", "👍", true),
        Form("mr", "‘%@’ वरून पसंती काढून टाकली आहे", "👍", true),
        Form("ms", "Mengeluarkan suka daripada “%@”", "👍", true),
        Form("nl", "Verwijderde een duim omhoog van '%@'", "👍", true),
        Form("no", "Liker ikke lenger «%@»", "👍", true),
        Form("or", "“%@”ରୁ ଗୋଟିଏ ଲାଇକ୍ କାଢ଼ିଛନ୍ତି", "👍", true),
        Form("pa", "”%@” ਤੋਂ ਪਸੰਦ ਨੂੰ ਹਟਾਇਆ ਗਿਆ", "👍", true),
        Form("pl", "Usunięto „kciuk w\u00a0górę” z\u00a0„%@”", "👍", true),
        Form("pt", "Removeu um curtiu de “%@”", "👍", true),
        Form("pt_PT", "Removeu Gosto de “%@”", "👍", true),
        Form("ro", "A eliminat o aprobare pentru „%@”", "👍", true),
        Form("ru", "«Нравится» убрано с\u00a0«%@»", "👍", true),
        Form("sk", "Z\u00a0„%@“ bolo odstránené označenie páči sa", "👍", true),
        Form("sl", "Z elementa »%@« je bila odstranjena oznaka »Všeč mi je«", "👍", true),
        Form("sv", "Tog bort ett gillande från ”%@”", "👍", true),
        Form("ta", "“%@”இலிருந்து விருப்பம் அகற்றப்பட்டது", "👍", true),
        Form("te", "“%@” నుండి లైక్ తొలగించబడింది", "👍", true),
        Form("th", "เอาถูกใจออกจาก “%@”", "👍", true),
        Form("tr", "Beğendi işareti silindi: “%@”", "👍", true),
        Form("uk", "Вилучено «подобається» з «%@»", "👍", true),
        Form("ur", "نے \u200f“%@” سے پسندیدگی کو ہٹایا", "👍", true),
        Form("vi", "Đã xóa thích khỏi “%@”", "👍", true),
        Form("zh_CN", "收回了赞：%@", "👍", true),
        Form("zh_HK", "不再讚好「%@」", "👍", true),
        Form("zh_TW", "已收回喜歡「%@」", "👍", true),
        Form("ar", "أزال(ت) عدم إعجاب عن \"%@\"", "👎", true),
        Form("bg", "Премахна нехаресване от „%@“", "👎", true),
        Form("bn", "“%@” থেকে একটি ডিসলাইক সরানো হয়েছে", "👎", true),
        Form("ca", "Ja no li desagrada “%@”.", "👎", true),
        Form("cs", "Z\u00a0„%@“ bylo odstraněno označení nelíbí", "👎", true),
        Form("da", "Fjernede et synes ikke om fra “%@”", "👎", true),
        Form("de", "„Gefällt mir nicht“ von „%@“ entfernt", "👎", true),
        Form("el", "Αφαίρεσε το «δεν μου αρέσει» από «%@»", "👎", true),
        Form("en", "Removed a dislike from “%@”", "👎", true),
        Form("es", "Ya no le disgusta “%@”", "👎", true),
        Form("es_419", "Dejó de no gustarle “%@”", "👎", true),
        Form("fi", "Viestistä ”%@” poistettiin ei-tykkäys", "👎", true),
        Form("fr", "A retiré son «\u00a0Je n’aime pas\u00a0» de «\u00a0%@\u00a0».", "👎", true),
        Form("fr_CA", "a retiré la mention «\u00a0N’aime pas\u00a0» de «\u00a0%@\u00a0»", "👎", true),
        Form("gu", "“%@”માંથી ડિસલાઇક કાઢી નાખી", "👎", true),
        Form("he", "הסיר/ה סימון ״לא אהבתי״ מ: ״%@״", "👎", true),
        Form("hi", "ने “%@” से नापसंद को हटाया", "👎", true),
        Form("hr", "Korisnik uklanja oznaku “Ne sviđa mi se” sa “%@”", "👎", true),
        Form("hu", "Eltávolított egy nemtetszést erről: „%@”", "👎", true),
        Form("id", "Menghapus tidak suka dari “%@”", "👎", true),
        Form("it", "Ha rimosso “Non mi piace” da “%@”", "👎", true),
        Form("ja", "“%@”から「よくないね」を削除", "👎", true),
        Form("kk", "«%@» дегеннен ұнатпау белгісін алып тастады", "👎", true),
        Form("kn", "“%@” ಸಂದೇಶದಿಂದ ಡಿಸ್\u200cಲೈಕ್ ತೆಗೆದುಹಾಕಿದ್ದಾರೆ", "👎", true),
        Form("ko", "‘%@’에서 별로예요 표시 제거함", "👎", true),
        Form("lt", "Pašalino žymėjimą, kad nepatinka „%@“", "👎", true),
        Form("ml", "‘%@’ എന്നതിൽ നിന്ന് ഡിസ്\u200cലൈക്ക് നീക്കം ചെയ്തു", "👎", true),
        Form("mr", "‘%@’ वरून नापसंत काढून टाकले आहे", "👎", true),
        Form("ms", "Mengeluarkan nyahsuka daripada “%@”", "👎", true),
        Form("nl", "Verwijderde een duim omlaag van '%@'", "👎", true),
        Form("no", "Misliker ikke lenger «%@»", "👎", true),
        Form("or", "“%@” ରୁ ଏକ ନାପସନ୍ଦକୁ କାଢ଼ିଛନ୍ତି", "👎", true),
        Form("pa", "“%@” ਤੋਂ ਨਾਪਸੰਦ ਨੂੰ ਹਟਾਇਆ ਗਿਆ", "👎", true),
        Form("pl", "Usunięto „kciuk w\u00a0dół” z\u00a0„%@”", "👎", true),
        Form("pt", "Removeu um não curtiu de “%@”", "👎", true),
        Form("pt_PT", "Removeu Não gosto de “%@”", "👎", true),
        Form("ro", "A eliminat o dezaprobare pentru „%@”", "👎", true),
        Form("ru", "«Не\u00a0нравится» убрано с\u00a0«%@»", "👎", true),
        Form("sk", "Z\u00a0„%@“ bolo odstránené označenie nepáči sa", "👎", true),
        Form("sl", "Z elementa »%@« je bila odstranjena oznaka »Ni mi všeč«", "👎", true),
        Form("sv", "Tog bort ett ogillande från ”%@”", "👎", true),
        Form("ta", "“%@”இலிருந்து விருப்பமின்மை அகற்றப்பட்டது", "👎", true),
        Form("te", "“%@” నుండి డిస్\u200cలైక్ తొలగించబడింది", "👎", true),
        Form("th", "เอาไม่ถูกใจออกจาก “%@”", "👎", true),
        Form("tr", "Beğenmedi işareti silindi: “%@”", "👎", true),
        Form("uk", "Вилучено «не подобається» з «%@»", "👎", true),
        Form("ur", "نے \u200f“%@” سے ناپسندیدگی کو ہٹایا", "👎", true),
        Form("vi", "Đã xóa không thích khỏi “%@”", "👎", true),
        Form("zh_CN", "收回了踩：%@", "👎", true),
        Form("zh_HK", "取消不喜歡「%@」", "👎", true),
        Form("zh_TW", "已收回不喜歡「%@」", "👎", true),
        Form("ar", "أزال(ت) ضحكة عن \"%@\"", "😂", true),
        Form("bg", "Премахна смеха от „%@“", "😂", true),
        Form("bn", "“%@” থেকে একটি হাসির প্রতিক্রিয়া সরানো হয়েছে", "😂", true),
        Form("ca", "Ja no li fa gràcia “%@”.", "😂", true),
        Form("cs", "Z\u00a0„%@“ byl odstraněn\u00a0smích", "😂", true),
        Form("da", "Fjernede et grin fra “%@”", "😂", true),
        Form("de", "Lachen von „%@“ entfernt", "😂", true),
        Form("el", "Αφαίρεσε το γέλιο από «%@»", "😂", true),
        Form("en", "Removed a laugh from “%@”", "😂", true),
        Form("es", "Ya no le hace gracia “%@”", "😂", true),
        Form("es_419", "Dejó de darle risa “%@”", "😂", true),
        Form("fi", "Viestistä ”%@” poistettiin naurahdus", "😂", true),
        Form("fr", "A retiré son rire de «\u00a0%@\u00a0».", "😂", true),
        Form("fr_CA", "a retiré la mention «\u00a0Rires\u00a0» de «\u00a0%@\u00a0»", "😂", true),
        Form("gu", "“%@”માંથી હાસ્ય કાઢી નાખ્યું", "😂", true),
        Form("he", "הסיר/ה צחקוק מ: ״%@״", "😂", true),
        Form("hi", "ने “%@” से ठहाके को हटाया", "😂", true),
        Form("hr", "Korisnik uklanja smijeh sa “%@”", "😂", true),
        Form("hu", "Eltávolított egy nevetést erről: „%@”", "😂", true),
        Form("id", "Menghapus tawa dari “%@”", "😂", true),
        Form("it", "Non trova più divertente “%@”", "😂", true),
        Form("ja", "“%@”から「笑」を削除", "😂", true),
        Form("kk", "«%@» дегеннен күлкіні алып тастады", "😂", true),
        Form("kn", "“%@” ಸಂದೇಶದಿಂದ ನಗುವನ್ನು ತೆಗೆದುಹಾಕಿದ್ದಾರೆ", "😂", true),
        Form("ko", "‘%@’에서 웃음 표시 제거함", "😂", true),
        Form("lt", "Pašalino „%@“ juoko jaustuką", "😂", true),
        Form("ml", "‘%@’ എന്നതിൽ നിന്ന് ചിരി നീക്കം ചെയ്തു", "😂", true),
        Form("mr", "‘%@’ वरून हसणे काढून टाकले आहे", "😂", true),
        Form("ms", "Mengeluarkan ketawa daripada “%@”", "😂", true),
        Form("nl", "Verwijderde een lach van '%@'", "😂", true),
        Form("no", "Fjernet latter fra «%@»", "😂", true),
        Form("or", "“%@” ରୁ ହସକୁ କାଢ଼ିଛନ୍ତି", "😂", true),
        Form("pa", "”%@” ਤੋਂ ਠਹਾਕਾ ਹਟਾਇਆ ਗਿਆ", "😂", true),
        Form("pl", "Usunięto „śmiech” z\u00a0„%@”", "😂", true),
        Form("pt", "Removeu uma risada de “%@”", "😂", true),
        Form("pt_PT", "Removeu um riso de “%@”", "😂", true),
        Form("ro", "A eliminat un râset pentru „%@”", "😂", true),
        Form("ru", "«Смешно» убрано с\u00a0«%@»", "😂", true),
        Form("sk", "Z\u00a0„%@“ bol odstránený smiech", "😂", true),
        Form("sl", "Z elementa »%@« je bila odstranjena oznaka »Smešno«", "😂", true),
        Form("sv", "Tog bort ett skratt från ”%@”", "😂", true),
        Form("ta", "“%@”இலிருந்து சிரிப்பு இமோஜி அகற்றப்பட்டது", "😂", true),
        Form("te", "“%@” నుండి నవ్వుతున్న ఎమోజీ తొలగించబడింది", "😂", true),
        Form("th", "เอาหัวเราะออกจาก “%@”", "😂", true),
        Form("tr", "Gülme işareti silindi: “%@”", "😂", true),
        Form("uk", "Вилучено «смішно» з «%@»", "😂", true),
        Form("ur", "نے \u200f“%@” سے ہنسی کو ہٹایا", "😂", true),
        Form("vi", "Đã xóa nụ cười khỏi “%@”", "😂", true),
        Form("zh_CN", "收回了哈哈：%@", "😂", true),
        Form("zh_HK", "不再覺得好笑：「%@」", "😂", true),
        Form("zh_TW", "已收回大笑「%@」", "😂", true),
        Form("ar", "أزال(ت) تعجبًا عن \"%@\"", "‼️", true),
        Form("bg", "Премахна удивителна от „%@“", "‼️", true),
        Form("bn", "“%@” থেকে একটি বিস্ময়বোধক চিহ্ন সরানো হয়েছে", "‼️", true),
        Form("ca", "L’ha deixat de sorprendre “%@”.", "‼️", true),
        Form("cs", "Z\u00a0„%@“ byl odstraněn vykřičník", "‼️", true),
        Form("da", "Fjernede et udråbstegn fra “%@”", "‼️", true),
        Form("de", "Ausrufezeichen von „%@“ entfernt", "‼️", true),
        Form("el", "Αφαίρεσε το θαυμαστικό από «%@»", "‼️", true),
        Form("en", "Removed an exclamation from “%@”", "‼️", true),
        Form("en_GB", "Removed an exclamation mark from “%@”", "‼️", true),
        Form("es", "Ya no le sorprende “%@”", "‼️", true),
        Form("es_419", "Dejó de exclamar por “%@”", "‼️", true),
        Form("fi", "Viestistä ”%@” poistettiin huutomerkki", "‼️", true),
        Form("fr", "A retiré ses points d’exclamation de «\u00a0%@\u00a0».", "‼️", true),
        Form("fr_CA", "a retiré la mention «\u00a0Exclamation\u00a0» de «\u00a0%@\u00a0»", "‼️", true),
        Form("gu", "“%@”માંથી ઉદ્ગારવાચક કાઢી નાખ્યું", "‼️", true),
        Form("he", "הסיר/ה סימני קריאה מ: ״%@״", "‼️", true),
        Form("hi", "ने “%@” से विस्मयादिबोधक हटाया", "‼️", true),
        Form("hr", "Korisnik uklanja uskličnik sa “%@”", "‼️", true),
        Form("hu", "Eltávolította a felkiáltójeleket erről: „%@”", "‼️", true),
        Form("id", "Menghapus tanda seru dari “%@”", "‼️", true),
        Form("it", "Ha rimosso i punti esclamativi da “%@”", "‼️", true),
        Form("ja", "“%@”から「!!」を削除", "‼️", true),
        Form("kk", "«%@» дегеннен леп белгісін алып тастады", "‼️", true),
        Form("kn", "“%1\$@” ಸಂದೇಶದಿಂದ ಆಶ್ಚರ್ಯಸೂಚಕವನ್ನು ತೆಗೆದುಹಾಕಿದ್ದಾರೆ", "‼️", true),
        Form("ko", "‘%@’에서 느낌표 표시 제거함", "‼️", true),
        Form("lt", "Pašalino „%@“ šauktuką", "‼️", true),
        Form("ml", "‘%@’ എന്നതിൽ നിന്ന് ആശ്ചര്യചിഹ്നം നീക്കം ചെയ്തു", "‼️", true),
        Form("mr", "‘%@’ वरून उद्\u200cगारवाचक चिन्ह काढून टाकले आहे", "‼️", true),
        Form("ms", "Mengeluarkan tanda seru daripada “%@”", "‼️", true),
        Form("nl", "Verwijderde een uitroepteken van '%@'", "‼️", true),
        Form("no", "Fjernet et utropstegn fra «%@»", "‼️", true),
        Form("or", "“%@” ରୁ ଏକ ବିସ୍ମୟ ସୂଚକ ଚିହ୍ନକୁ କାଢ଼ିଛନ୍ତି", "‼️", true),
        Form("pa", "”%@” ਤੋਂ ਵਿਸਮਿਕ ਚਿੰਨ੍ਹ ਨੂੰ ਹਟਾਇਆ ਗਿਆ", "‼️", true),
        Form("pl", "Usunięto „wykrzykniki” z\u00a0„%@”", "‼️", true),
        Form("pt", "Removeu uma exclamação de “%@”", "‼️", true),
        Form("ro", "A eliminat o exclamație pentru „%@”", "‼️", true),
        Form("ru", "Восклицательный знак убран с\u00a0«%@»", "‼️", true),
        Form("sk", "Z\u00a0„%@“ bol odstránený výkričník", "‼️", true),
        Form("sl", "Z elementa »%@« je bila odstranjena oznaka s klicajem", "‼️", true),
        Form("sv", "Tog bort utropstecken från ”%@”", "‼️", true),
        Form("ta", "“%@”இலிருந்து ஆச்சரியக்குறி அகற்றப்பட்டது", "‼️", true),
        Form("te", "“%@” నుండి ఆశ్చర్యార్థక గుర్తు తొలగించబడింది", "‼️", true),
        Form("th", "เอาเครื่องหมายตกใจออกจาก “%@”", "‼️", true),
        Form("tr", "Ünlem işareti silindi: “%@”", "‼️", true),
        Form("uk", "Вилучено знаки оклику із «%@»", "‼️", true),
        Form("ur", "نے \u200f“%@” سے فجائیہ کو ہٹایا", "‼️", true),
        Form("vi", "Đã xóa dấu chấm than khỏi “%@”", "‼️", true),
        Form("zh_CN", "收回了惊叹：%@", "‼️", true),
        Form("zh_HK", "不再驚嘆「%@」", "‼️", true),
        Form("zh_TW", "已收回驚嘆「%@」", "‼️", true),
        Form("ar", "أزال(ت) علامة استفهام عن \"%@\"", "❓", true),
        Form("bg", "Премахна въпросителна от „%@“", "❓", true),
        Form("bn", "“%@” থেকে একটি প্রশ্নবোধক চিহ্ন সরানো হয়েছে", "❓", true),
        Form("ca", "Ja no té dubtes sobre “%@”.", "❓", true),
        Form("cs", "Z\u00a0„%@“ byl odstraněn otazník", "❓", true),
        Form("da", "Fjernede et spørgsmålstegn fra “%@”", "❓", true),
        Form("de", "Fragezeichen von „%@“ entfernt", "❓", true),
        Form("el", "Αφαίρεσε το ερωτηματικό από «%@»", "❓", true),
        Form("en", "Removed a question mark from “%@”", "❓", true),
        Form("es", "Ya no duda sobre “%@”", "❓", true),
        Form("es_419", "Dejó de dudar sobre “%@”", "❓", true),
        Form("fi", "Viestistä ”%@” poistettiin kysymysmerkki", "❓", true),
        Form("fr", "A retiré son point d’interrogation de «\u00a0%@\u00a0».", "❓", true),
        Form("fr_CA", "a retiré la mention «\u00a0Question\u00a0» de «\u00a0%@\u00a0»", "❓", true),
        Form("gu", "“%@”માંથી પ્રશ્નાર્થ ચિહ્ન કાઢી નાખ્યું", "❓", true),
        Form("he", "הסיר/ה סימן שאלה מ: ״%@״", "❓", true),
        Form("hi", "ने “%@” से प्रश्न चिह्न हटाया", "❓", true),
        Form("hr", "Korisnik uklanja upitnik sa “%@”", "❓", true),
        Form("hu", "Eltávolította a kérdőjelet erről: „%@”", "❓", true),
        Form("id", "Menghapus tanda tanya dari “%@”", "❓", true),
        Form("it", "Ha rimosso il punto interrogativo da “%@”", "❓", true),
        Form("ja", "“%@”から「?」を削除", "❓", true),
        Form("kk", "«%@» дегеннен сұрақ белгісін алып тастады", "❓", true),
        Form("kn", "“%@” ಸಂದೇಶದಿಂದ ಪ್ರಶ್ನಾರ್ಥಕ ಚಿಹ್ನೆಯನ್ನು ತೆಗೆದುಹಾಕಿದ್ದಾರೆ", "❓", true),
        Form("ko", "‘%@’에서 물음표 표시 제거함", "❓", true),
        Form("lt", "Pašalino „%@“ klaustuką", "❓", true),
        Form("ml", "‘%@’ എന്നതിൽ നിന്ന് ചോദ്യചിഹ്നം നീക്കം ചെയ്തു", "❓", true),
        Form("mr", "‘%@’ वरून प्रश्नचिन्ह काढून टाकले आहे", "❓", true),
        Form("ms", "Mengeluarkan tanda soal daripada “%@”", "❓", true),
        Form("nl", "Verwijderde een vraagteken van '%@'", "❓", true),
        Form("no", "Fjernet et spørsmålstegn fra «%@»", "❓", true),
        Form("or", "“%@”ରୁ ଏକ ପ୍ରଶ୍ନ ଚିହ୍ନ କାଢ଼ିଛନ୍ତି", "❓", true),
        Form("pa", "”%@” ਤੋਂ ਸਵਾਲੀਆ ਚਿੰਨ੍ਹ ਨੂੰ ਹਟਾਇਆ ਗਿਆ", "❓", true),
        Form("pl", "Usunięto „znak zapytania” z\u00a0„%@”", "❓", true),
        Form("pt", "Removeu um ponto de interrogação de “%@”", "❓", true),
        Form("ro", "A eliminat un semn de întrebare pentru „%@”", "❓", true),
        Form("ru", "Вопрос убран с\u00a0«%@»", "❓", true),
        Form("sk", "Z\u00a0„%@“ bol odstránený otáznik", "❓", true),
        Form("sl", "Z elementa »%@« je bila odstranjena oznaka z vprašajem", "❓", true),
        Form("sv", "Tog bort ett frågetecken från ”%@”", "❓", true),
        Form("ta", "“%@”இலிருந்து கேள்விக்குறி அகற்றப்பட்டது", "❓", true),
        Form("te", "“%@” నుండి ప్రశ్నార్థక గుర్తు తొలగించబడింది", "❓", true),
        Form("th", "เอาเครื่องหมายคำถามออกจาก “%@”", "❓", true),
        Form("tr", "Soru işareti silindi: “%@”", "❓", true),
        Form("uk", "Вилучено «знак питання» з «%@»", "❓", true),
        Form("ur", "نے \u200f“%@” سے سوالیہ نشان ہٹایا", "❓", true),
        Form("vi", "Đã xóa dấu chấm hỏi khỏi “%@”", "❓", true),
        Form("zh_CN", "收回了疑惑：%@", "❓", true),
        Form("zh_HK", "不再疑惑「%@」", "❓", true),
        Form("zh_TW", "已收回疑惑「%@」", "❓", true),
        Form("ar", "تفاعل(ت) %@ على \"%@\"", "", false),
        Form("bg", "Реакция: %@ на „%@“", "", false),
        Form("bn", "“%2\$@”-এ %1\$@ প্রতিক্রিয়া দিয়েছেন", "", false),
        Form("ca", "%@ afegit a: “%@”", "", false),
        Form("cs", "Přidána reakce %@ ke zprávě „%@“", "", false),
        Form("da", "Reagerede med %@ på “%@”", "", false),
        Form("de", "Hat mit %@ auf „%@“ reagiert", "", false),
        Form("el", "Αντέδρασε με %@ σε «%@»", "", false),
        Form("en", "Reacted %@ to “%@”", "", false),
        Form("es", "Se ha reaccionado con %@ a “%@”", "", false),
        Form("es_419", "Reaccionó con %@ a “%@”", "", false),
        Form("fi", "Reagoi %@ viestiin”%@”", "", false),
        Form("fr", "A réagi avec %@ à «\u00a0%@\u00a0»", "", false),
        Form("fr_CA", "A réagi %@ à «\u00a0%@\u00a0»", "", false),
        Form("gu", "“%2\$@” પર %1\$@ પ્રતિક્રિયા આપવામાં આવી", "", false),
        Form("he", "הגיב/ה עם %@ ל-״%@״", "", false),
        Form("hi", "“%2\$@” पर %1\$@ प्रतिक्रिया दी", "", false),
        Form("hr", "Reagira s “%@” na “%@”", "", false),
        Form("hu", "%@ reakciót fűzött a következőhöz: „%@”", "", false),
        Form("id", "Bereaksi %@ terhadap “%@”", "", false),
        Form("it", "Ha reagito con %@ a “%@”", "", false),
        Form("ja", "“\u200a%2\$@\u200a”に\u200a%1\$@\u200aでリアクションしました", "", false),
        Form("kk", "«%2\$@» дегенге %1\$@ деп жауап қайтарды", "", false),
        Form("kn", "“%@”ಗೆ %@ ಎಂದು ಪ್ರತಿಕ್ರಿಯಿಸಲಾಗಿದೆ", "", false),
        Form("ko", "‘%2\$@’에 %1\$@ 표시로 반응함", "", false),
        Form("lt", "sureaguota %@ į „%@“", "", false),
        Form("ml", "‘%@’ എന്നതിനോട് %@ എന്ന് പ്രതികരിച്ചു", "", false),
        Form("mr", "‘%@’ वर %@ प्रतिक्रिया दिली", "", false),
        Form("ms", "Memberi reaksi %@ kepada “%@”", "", false),
        Form("nl", "Reageerde met %@ op '%@'", "", false),
        Form("no", "Reagerte med %@ på «%@»", "", false),
        Form("or", "“%@”ରେ %@ ପ୍ରତିକ୍ରିୟା ଦେଇଛନ୍ତି", "", false),
        Form("pa", "“%@” ’ਤੇ %@ ਪ੍ਰਤਿਕਿਰਿਆ ਦਿੱਤੀ", "", false),
        Form("pl", "Dodaje reakcję (%@) do „%@”", "", false),
        Form("pt", "Reagiu com %@ a “%@”", "", false),
        Form("pt_PT", "Reagiu com “%@” a “%@”", "", false),
        Form("ro", "A reacționat cu %@ la „%@”", "", false),
        Form("ru", "Отреагировал(а) %@ на\u00a0сообщение «%@»", "", false),
        Form("sk", "Pridaná reakcia %@ na „%@“", "", false),
        Form("sl", "Se je na %@ odzval(-a) s/z “%@”", "", false),
        Form("sv", "reagerade med %@ på ”%@”", "", false),
        Form("ta", "“%@”க்கு %@ என்று ரியாக்ட் செய்யப்பட்டது", "", false),
        Form("te", "“%2\$@”కు %1\$@ అని ప్రతిస్పందించారు", "", false),
        Form("th", "โต้ตอบด้วย %@ กับ “%@”", "", false),
        Form("tr", "“%2\$@” için %1\$@ tepkisi verildi", "", false),
        Form("uk", "Додано реакцію «%@» на «%@»", "", false),
        Form("ur", "\u200f“%2\$@” پر %1\$@ کے ذریعے رد عمل ظاہر کیا", "", false),
        Form("vi", "Đã tương tác %@ cho “%@”", "", false),
        Form("zh_CN", "用%@回应了“%@”", "", false),
        Form("zh_HK", "已用%1\$@回應「%2\$@」", "", false),
        Form("ar", "أزال(ت) \u200c%@\u200c من \"\u200a%@\"", "", true),
        Form("bg", "Премахна %@ от „%@“", "", true),
        Form("bn", "“%2\$@” থেকে %1\$@ অপসারণ করা হয়েছে", "", true),
        Form("ca", "%@ eliminat de: “%@”", "", true),
        Form("cs", "Odstraněna reakce %@ z\u00a0„%@“", "", true),
        Form("da", "Fjernede %@ fra “%@”", "", true),
        Form("de", "Hat %@ von „%@“ entfernt", "", true),
        Form("el", "Αφαίρεσε «%@» από «%@»", "", true),
        Form("en", "Removed %@ from “%@”", "", true),
        Form("es", "Ha eliminado %@ de “%@”.", "", true),
        Form("es_419", "Eliminó %@ de “%@”", "", true),
        Form("fi", "Poistettiin %@ viestistä ”%@”", "", true),
        Form("fr", "A retiré %@ de «\u00a0%@\u00a0»", "", true),
        Form("fr_CA", "a retiré la réaction %@ de «\u00a0%@\u00a0»", "", true),
        Form("gu", "“%1\$@”માંથી %2\$@ કાઢી નાખવામાં આવ્યું", "", true),
        Form("he", "הסיר/ה %@ מההודעה ״%@״", "", true),
        Form("hi", "“%1\$@” से %2\$@ को हटाया गया", "", true),
        Form("hr", "Uklanja %@ iz “%@”", "", true),
        Form("hu", "Eltávolította a %@ reakciót a következőről: „%@”", "", true),
        Form("id", "Menghapus %@ dari “%@”", "", true),
        Form("it", "Ha rimosso %@ da “%@”", "", true),
        Form("ja", "“%2\$@”から %1\$@ を削除しました", "", true),
        Form("kk", "«%2\$@» дегеннен %1\$@ алып тасталды", "", true),
        Form("kn", "“%2\$@” ಸಂದೇಶದಿಂದ %1\$@ ಅನ್ನು ತೆಗೆದುಹಾಕಿದ್ದಾರೆ", "", true),
        Form("ko", "‘%2\$@’에서 %1\$@ 표시 제거함", "", true),
        Form("lt", "Pašalino „%@“ iš „%@“", "", true),
        Form("ml", "‘%2\$@’ എന്നതിൽ നിന്ന് %1\$@ നീക്കം ചെയ്തു", "", true),
        Form("mr", "’%2\$@’ मधून %1\$@ काढून टाकले", "", true),
        Form("ms", "Mengeluarkan %@ daripada “%@”", "", true),
        Form("nl", "Verwijderde %@ uit '%@'", "", true),
        Form("no", "Fjernet %@ fra «%@»", "", true),
        Form("or", "%1\$@ରୁ %2\$@କୁ କାଢ଼ି ଦେଇଛନ୍ତି", "", true),
        Form("pa", "“%1\$@” ਤੋਂ %2\$@ ਨੂੰ ਹਟਾਇਆ ਗਿਆ", "", true),
        Form("pl", "Usuwa „%@” z\u00a0„%@”", "", true),
        Form("pt", "Removeu %@ de “%@”", "", true),
        Form("ro", "A eliminat %@ pentru „%@”", "", true),
        Form("ru", "Убирает реакцию %@ с\u00a0сообщения «%@»", "", true),
        Form("sk", "Odstraňuje reakciu %@ z\u00a0„%@“", "", true),
        Form("sl", "Odstranil(-a) %@ iz besedila »%@«", "", true),
        Form("sv", "Tog bort %@ från ”%@”", "", true),
        Form("ta", "“%@”இல் இருந்து %@ அகற்றப்பட்டது", "", true),
        Form("te", "“%@” నుండి %@\u200cను తొలగించారు", "", true),
        Form("th", "เอา %@ ออกจาก “%@”", "", true),
        Form("tr", "“%2\$@” mesajından %1\$@ tepkisi silindi", "", true),
        Form("uk", "Вилучено «%@» з «%@»", "", true),
        Form("ur", "\u200f”%1\$@” سے %2\$@ ہٹایا", "", true),
        Form("vi", "Đã xóa %@ khỏi “%@”", "", true),
        Form("zh_CN", "收回了%@：%@", "", true),
        Form("zh_HK", "不再用%1\$@回應「%2\$@」", "", true),
        Form("zh_TW", "已收回用%1\$@回應「%2\$@」", "", true),
    )
}
